rainbow:
  file:
    root: /data/classified_img

eureka:
  client:
    serviceUrl:
      defaultZone: http://119.29.208.119:8761/eureka/
server:
  port: 8765
  ssl:
      key-store: classpath:www.kebencool.cn.jks
      key-store-password: 1464q178c0lp330
      keyStoreType: JKS

multipart:
  maxFileSize: 10Mb
  maxRequestSize: 50Mb
#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources

mybatis:
  typeAliasesPackage: com.discern.car.dao
  mapperLocations: classpath*:mapper/*.xml


#开发配置
spring:
  #  profiles: dev
  profiles:
    active: dev
  datasource:
    # 配置数据源类型
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://119.29.208.119:3306/car?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useSSL=false&autoReconnect=true
    #    url: jdbc:mysql://119.29.208.119:3306/car?useUnicode=true&characterEncoding=utf8mb4&rewriteBatchedStatements=true&useSSL=false
    username: xiaoxu
    password: xiaoxu
    # 初始化，最小，最大连接数
    initialSize: 3
    minidle: 3
    maxActive: 18
    # 获取数据库连接等待的超时时间
    maxWait: 60000
    # 配置多久进行一次检测，检测需要关闭的空闲连接 单位毫秒
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1
    druid:
      connection-init-sqls: set names utf8mb4;
      test-while-idle: true
      min-evictable-idle-time-millis: 300000

  #    hikari:
  #
  #          connection-init-sql: set names utf8mb4;
  #          minimum-idle : 2
  #          maximum-pool-size : 4
  #          auto-commit : true
  ##         指定连接多久没被使用时，被设置为空闲，默认为10ms
  #          idle-timeout: 10000
  #          pool-name: DatebookHikariCP
  ##          指定连接池中连接的最大生存时间，毫秒单位.
  #
  #          max-lifetime: 1800000
  ##          指定连接的超时时间，毫秒单位.
  #          connection-timeout: 50000
  #          connection-test-query: SELECT 1;
  #

  application:
    name: classify_servic
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 119.29.208.119
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: abc012300
    # 连接池最大连接数（使用负值表示没有限制）

    jedis:
      pool:
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 60
        # 连接池中的最小空闲连接
        min-idle: 30
    # 连接超时时间（毫秒）
#    timeout: 5000
